# Generated by Django 2.2.1 on 2019-05-28 12:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voters', '0001_initial'),
        ('participants', '0002_auto_20190524_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(12)])),
                ('from_voter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='voters.Voter')),
                ('to_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Participant')),
            ],
        ),
    ]
