# Generated by Django 2.2.1 on 2019-05-23 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0002_auto_20190522_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField(default=0)),
                ('from_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_votes', to='countries.Country')),
                ('to_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_votes', to='countries.Country')),
            ],
        ),
    ]
