# Generated by Django 2.2.1 on 2019-05-23 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='point',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
