# Generated by Django 2.2.1 on 2019-05-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='to_country',
            new_name='to_participant',
        ),
    ]
