# Generated by Django 2.2.1 on 2019-05-24 07:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20190523_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='point',
            field=models.PositiveIntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='vote',
            name='to_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_votes', to='participants.Participant'),
        ),
    ]
