# Generated by Django 2.2.1 on 2019-07-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20190530_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='to_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='participants.Participant'),
        ),
    ]
