# Generated by Django 2.2.1 on 2019-05-27 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_auto_20190524_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='from_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='to_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.Participant'),
        ),
    ]
