# Generated by Django 2.2.1 on 2019-05-28 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
        ('votes', '0006_auto_20190527_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='from_country',
        ),
        migrations.AddField(
            model_name='vote',
            name='from_voter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='voters.Voter'),
        ),
    ]
