# Generated by Django 2.2.1 on 2019-05-24 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='contest_id',
            new_name='contest',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='country_id',
            new_name='country',
        ),
    ]
