# Generated by Django 2.2.1 on 2019-06-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_auto_20190530_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
