# Generated by Django 2.2.1 on 2019-06-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_participant_total_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='total_score',
        ),
    ]
