# Generated by Django 2.2.1 on 2019-07-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_remove_participant_total_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={},
        ),
    ]
