# Generated by Django 2.2.1 on 2019-05-22 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20190522_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='year',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(2019), django.core.validators.MinValueValidator(1956)]),
        ),
    ]
